### PR TITLE
fix: remove the generic on _CapsuleManager to allow capsule upcasts

### LINKED ISSUE #36: Internal error when using inherited types
An example is the easiest:

```dart
class A {}
class B implements A {}

B myCapsule(CapsuleHandle use) {
  final (value, setValue) = use.state(B());
}

void later() {
  final valueA = use(myCapsule as A);
  final valueB = use(myCapsule); // Will throw error
}
```

```
#0      CapsuleContainer._managerOf (package:rearch/rearch.dart:133:7)
rearch.dart:133
#1      _CapsuleManager.read (package:rearch/src/impl.dart:35:36)
impl.dart:35
#2      _CapsuleHandleImpl.call (package:rearch/src/impl.dart:111:20)
impl.dart:111
#3      CapsuleContainer.onNextUpdate.tempCapsule (package:rearch/rearch.dart:184:47)
rearch.dart:184
#4      _CapsuleManager.buildSelf (package:rearch/src/impl.dart:52:30)
impl.dart:52
#5      new _CapsuleManager (package:rearch/src/impl.dart:9:5)
impl.dart:9
#6      CapsuleContainer._managerOf.<anonymous closure> (package:rearch/rearch.dart:132:13)
rearch.dart:132
#7      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
compact_hash.dart:543
#8      CapsuleContainer._managerOf (package:rearch/rearch.dart:130:22)
rearch.dart:130
#9      CapsuleContainer.onNextUpdate (package:rearch/rearch.dart:185:25)
rearch.dart:185
#10     _WidgetHandleImpl.call (package:flutter_rearch/src/widgets/consumer.dart:145:31)
consumer.dart:145
```

### PR DESCRIPTION
**Pull request by GregoryConrad**
Fixes #36

### CODE REVIEW

**Comment by busslina** [comment]
Will this enhancement will allow to remove the generics here?

```dart
List<Module> allModules(CapsuleHandle use) => [
      use<EventsModule>(eventsModule),
      use<PluginsModule>(pluginsModule),
      use<ResourcesModule>(resourcesModule),
      use<LoggingModule>(loggingModule),
    ];
```

**Comment by GregoryConrad** [comment]
@busslina Yup! You shouldn't need to ever specify the generics again.

**Comment by GregoryConrad** [comment]
And you can also simplify that to `[eventsModule, pluginsModule, resourcesModule, loggingModule].map(use).toList()` now!

**Comment by busslina** [comment]
That's great!

**Pull request merged**
