### PR TITLE
fix: force lazyStateGetterSettter dependents to rebuild on state change

### LINKED ISSUE #32: [DOC CHANGE PROPOSAL]
https://github.com/GregoryConrad/rearch-dart/blob/b39cd673c06c932208c8d620db2eadd36c282300/packages/rearch/lib/src/side_effects.dart#L50C34-L50C34

Maybe specify that it keeps the same `getter` across rebuilds too

### PR DESCRIPTION
**Pull request by GregoryConrad**
Also fixes #32

### CODE REVIEW

**Comment by busslina** [comment]
So now we have to take care that we have always the last version of the getter. To not cache it

**Comment by busslina** [comment]
I propose you an alternative solution. To specify in the API.rebuild() a false by default argument to disallow equality check.

I have to review my code, but maybe I was catching the getter somewhere.

What do you think about this?

**Comment by busslina** [comment]
I propose you an alternative solution. To specify in the API.rebuild() a false by default argument to disallow equality check.

I have to review my code, but maybe I was catching the getter somewhere.

What do you think about this?

**Comment by busslina** [comment]
But I understand it could be tricky and a bad practice.

**Comment by GregoryConrad** [comment]
> So now we have to take care that we have always the last version of the getter. To not cache it

You can use whatever version of the getter you like; they’ll all work. Only issue is the reactivity of dependencies, which is why I made that change yesterday. Feel free to cache it, just be careful t that you don’t then return a cached copy as your capsule’s data.

> To specify in the API.rebuild() a false by default argument to disable equality check.

This will result in the same issue, but just pushed down to the next level of capsules (unless you force rebuild the entire dependents subgraph, but I don’t really think that’s a good idea).

**Pull request merged**
